### ISSUE TITLE
Loses hook to target when files loaded from different directories

### ISSUE THREAD

**Issue by Rich-YoYo** [mbbill/undotree#88] opened 2018-08-23 10:20 UTC
To reproduce;-

- Load a file 'A' from a directory ./a/
- In a new window, load a file 'B' from a (different) directory ./b/
- Open undotree
- Move focus between 'A' and 'B' - undotree updates as expected
- Move focus to 'B' and then move focus to undotree - undotree display persists as expected
- Move focus to 'A' and then move focus to undotree - undotree disappears - not as expected

ie - if the undotree window is in focus, then undo data disappears if it relates to a file from a different directory to that of the the last file loaded. The number of files involves doesn't seem to matter; taking the above example, if several files were loaded from ./a/ then they would all exhibit this problem

Note that undotree data is always displayed correctly as long as its own window is NOT in focus

I have recently added a function to undotree to allow me to retrieve the window Id that it is displaying undo information for (so that I can add it to undotree's status bar). From this, I can see that when undotree data disappears (when its window is in focus), its internal 'focusid' (window Id) is set to itself rather than to the buffer who's undo data it is displaying. Once focus moves away from undotree, 'focusid' is corrected again.

I wondered if the problem could be related to my use of 'set autochdir' but it seems to make no difference

**Comment by mbbill** [comment] 2018-08-23 17:54
It seems like it is related to the ```autochdir``` setting. I can only reproduce the issue when ```autochdir``` is turned on. But still it's bug anyways, let me take a deeper look.
Thanks for the bug report!

**Comment by mbbill** [comment] 2018-08-23 18:43
fixed in b1b7667a1f2e52f61eab21ef86622dcf412ba431
the reason is the ```autochdir``` option will sometimes change the return value of bufname('%') which I used to tell if that buffer is belong to the undotree. When ```autochdir``` is turned off, the bufname('%') will always return *undotree_id* but with that option turned on, it becomes ```/path/to/some/dir/undotree_id```
Now I'm using a buffer value instead so that it won't be affected by buffer name anymore.

**Closed** 2018-08-23 18:43 UTC
Labels: bug

**Comment by Rich-YoYo** [comment] 2018-08-23 19:53
On Thu, 23 Aug 2018 18:43:40 +0000 (UTC)
"Ming, Bai" <notifications@github.com> wrote:

> Closed #88.
> 

Brilliant! Thanks for the fix

regards

Rich
