### ISSUE TITLE
Error detected while switching: ID not found 

### ISSUE THREAD

**Issue by clouduan** [mbbill/undotree#87] opened 2018-08-18 15:16 UTC
I opened `undotree` and typed <CR> to view my history, and got that error:
![photo_2018-08-18_23-05-04](https://user-images.githubusercontent.com/20282795/44300579-de227c00-a33b-11e8-9933-8e1b10c7886f.jpg)
But surprisingly, after I pressed ENTER again, I switched to that history successfully. Now can I only get rid of that error message?

I've debugged using the log file, but found nothing about it. Please help.
This is the part of my `vimrc`:
```
set history=2000

set noautochdir
set modifiable

set autoread
set autowrite
set updatetime=100
set nospell

set nobackup
set noswapfile
set nowritebackup
set undodir=~/.vim/undo_dir/
set undofile
```
Thanks for this fantastic plugin!

**Comment by mbbill** [comment] 2018-08-19 04:31
Thanks for the bug report!
Does it always happen? or just on your vimrc? Or it would be better if you can provide a guide for how to reproduce the issue.

**Comment by clouduan** [comment] 2018-08-19 04:49
Thanks for your response!
When I simplified my `.vimrc` to as much as possible, I found that issue was gone. So I think that my `vimrc`  brought about that issue. I will use exclusive method to found the bug of my vimrc as soon as possible.

**Comment by mbbill** [comment] 2018-08-19 05:06
thanks but no hurry! the E803 is caused by matchdelete(), so you might take a look at some related settings in your vimrc.

**Comment by clouduan** [comment] 2018-08-19 05:46
If you want to figure out what's wrong with that, you can install and try it. But it seems that vim-coloresque was deprecated for a long time...
Anyway, I switched to [vim-css-color](https://github.com/ap/vim-css-color), and everything is going pretty well. 
Thank you for help!

**Comment by mbbill** [comment] 2018-08-20 03:37
Good! closing the issue then..

**Closed by mbbill** 2018-08-20 03:37 UTC
